image: node:16.19.1
  
ports:
  - port: 4200

tasks:
  - name: postgres
    command: cd src && file .gitpod.yml
  - name: frontend
    init: npm install
    command: npm install && npm run start-local 

             
